# image:
image: hpcer/hpcdev:pkg-0.3.0

cache:
  key: vendor_version_libcomm_0.3.2_2  # change this key if vendor changed.
  paths:
    - vendor/src

stages:
  - fetch
  - build
  - test
  - deploy

fetch:
  stage: fetch
  tags:
    - cpp
    - pkg
  variables:
    PKG_AUTH: 'gitlab-ci-token?${CI_JOB_TOKEN}@git.hpcer.dev'
  script:
    - pkg fetch
    - pkg install --verbose
  artifacts:
    untracked: true

build:
  stage: build
  tags:
    - cpp
    - pkg
  script:
    - cmake -Bcmake-build -DCMAKE_BUILD_TYPE=Debug -H.
    - make -Ccmake-build
  artifacts:
    untracked: true
  dependencies:
    - fetch

test:
  stage: test
  tags:
    - cpp
    - pkg
  script:
    - GTEST_OUTPUT=xml:report-abvi.xml GTEST_COLOR=yes ./cmake-build/bin/abvi-model-unit-tests
    - GTEST_OUTPUT=xml:report-pkmc.xml GTEST_COLOR=yes ./cmake-build/bin/pkmc-unit-tests
    # - cd cmake-build
    # - GTEST_COLOR=yes make test ARGS=-V
    - gcovr --exclude tests --exclude vendor
    - echo "saving code coverage reports to html files."
    - mkdir -p coverage # save coverage report html files.
    - gcovr --html-details --exclude tests --exclude vendor -o coverage/index.html --print-summary
  dependencies:
    - build
  artifacts:
    paths:
      - coverage/  # save coverage report html files.
    reports:
      junit:
        - report-abvi.xml
        - report-pkmc.xml

# code_quality: https://docs.gitlab.com/ee/ci/examples/code_quality.html#previous-job-definitions

pages:
  stage: deploy
  tags:
    - pages
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
  only:
    - master
    - dev